cors:
  originPatterns: http://localhost:3000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  application:
    name: ApiIntegracao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/apiintegracao?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      format_sql: true
  flyway:
    enabled: false
server:
  port: 8080
springdoc:
  pathsToMatch:
    - /health/**
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true
    tags-sorter: alpha
    operations-sorter: alpha
logging:
  file:
    name: api.log
descobertaLocal: false