cors:
  originPatterns: http://localhost:3000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  flyway:
    enabled: false
  datasource:
    api:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/apiintegracao?useTimezone=true&serverTimezone=UTC
      jdbc-url: jdbc:mysql://localhost:3306/apiintegracao?useTimezone=true&serverTimezone=UTC
      username: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
datasource:
  decksubtitle:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/decksubtitle?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin
  mangaextractor:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manga_extractor?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin
  textoingles:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/texto_ingles?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
  textojapones:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/texto_japones?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
server:
  port: 8080
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true
logging:
  file:
    name: api.log