spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apiintegra?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
springdoc:
  pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true